data:
  data_dir: "data/"
  train_file: "preprocessed/temperature/lite_sample/X.npy"
  label_file: "preprocessed/temperature/lite_sample/y.npy"
  val_points: 10
  train_split: 0.8

features:
  window_size: 20
  sampling_rate: 1
  stride: 1
  n_neighbors: 4

model:
  type: "RegressionTCNv0"  # or "SpatialRegressionTCNv1"
  feature_dim: 9
  output_dim: 3
  hidden_channels: [64, 64, 64, 64, 64, 64]
  network_depth: 6
  filter_width: 4
  dropout: 0.2
  activation: "relu"
  use_skip_connections: false
  spatial_dim: 3
  spatial_embedding_dim: 16
  time_dim: 20  # window_size

training:
  batch_size: 32 
  num_epochs: 100
  learning_rate: 1e-3
  loss_function: "mse"  # or "mae"
  resume_from_checkpoint: false
  resume_checkpoint: "model_epoch_100.pth"  # Specify the checkpoint file to resume from
  checkpoint_dir: "training_checkpoints/tcn_lite/"

inference:
  batch_size: 128
  device: "auto"

wandb:
  project: "tcn_lite"
  log_interval: 1
  save_interval: 10 

device: "auto"  # "cuda", "mps", or "cpu"
random_seed: 42